// AUTO-GENERATED by scripts/sync-events.mjs — do not edit directly.
// Run `npm run sync-events` to refresh from beachcomberhotelandresort.com.au/whats-on/.
// Last synced: 2026-08-26T05:53:42.259Z

export interface FeaturedEvent {
  title: string;
  /** Plain text, stripped of the source page-builder markup. */
  description: string;
  image: string | null;
  /** Booking / more-info link, when the tile has one. */
  url: string | null;
}

export interface WeeklyEvent {
  title: string;
  description: string;
  image: string | null;
}

export interface LiveSportsWidgets {
  /** Small "what's on now" carousel embed. */
  carouselUrl: string;
  /** Full fixtures/results widget embed. */
  fullUrl: string;
}

export const featuredEvents: FeaturedEvent[] = [
  {
    "title": "HUNGERFORD HILL WINE DINNER",
    "description": "Friday 28 August. Join us at Pelicans for an intimate five-course dinner paired with premium wines from Hungerford Hill, straight from the Hunter Valley, with the winemaking team on hand throughout the evening",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2026/08/Hungerford-Hill-Wine-Dinner-Square-300x300.png",
    "url": "https://www.sevenrooms.com/xBWccU76"
  },
  {
    "title": "FATHER’S DAY",
    "description": "Sunday 6 September. Book a table on the terrace for lunch by the lake. Buy Dad a main meal and his first Great Northern Super Crisp is on us, plus buy any Great Northern to go in the draw for a Dad’s Pack.",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2026/08/Beachomber-FathersDay-26_Square-1-300x300.png",
    "url": null
  },
  {
    "title": "FOOTY FINALS",
    "description": "Every game live and loud on the big screens. Book a table, settle in with chips and a pint of VB for $16, and grab any 2 VB or a jug to share for your chance to win a double pass to the 2026 NRL Grand Final.",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2026/08/Beachie_Footy-Finals_Static_Digital_310726_StaticTile-300x300.jpg",
    "url": "https://beachcomberhotelandresort.com.au/event/footy-finals-at-the-beachie/"
  }
];

export const weeklyEvents: WeeklyEvent[] = [
  {
    "title": "POOL COMP",
    "description": "Line up your best shot every Thursday from 7pm at our weekly Pool Comp. Bring your crew and play for a prize pool that’s worth it.",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2025/05/67-300x300.png"
  },
  {
    "title": "LIVE ENTERTAINMENT",
    "description": "Enjoy a live soloists every Friday and Sunday! Relax lakeside with smooth tunes, good food, and even better company.",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2025/01/BEACHIE-Entertainment-300x300.jpg"
  },
  {
    "title": "SATURDAY SESSIONS",
    "description": "A mix of local bands and DJs take over Saturday nights from 7pm. Grab a drink and settle in. Entry is free!",
    "image": "https://beachcomberhotelandresort.com.au/wp-content/uploads/2025/01/BEACHIE-Entertainment-1-300x300.jpg"
  }
];

/** The venue's live-music booking widget (surreal.live), embedded as-is. */
export const liveEntertainmentWidgetUrl: string = "https://surreal.live/widget/the-beachcomber-hotel-and-resort-ascend-hotel-collection";

export const liveSportsWidgets: LiveSportsWidgets = {
  "carouselUrl": "https://sportsyear.com.au/promo/carousel/?c=3dab7ca09d4f60daaae8c80367c9e7cc9de0cdd3304ada48ea74a9e6ddad22f7&theme=auto&profile=mma-rugby-league&timezone=Australia%2FSydney",
  "fullUrl": "https://sportsyear.com.au/widget/?c=3dab7ca09d4f60daaae8c80367c9e7cc9de0cdd3304ada48ea74a9e6ddad22f7"
};
